// <auto-generated />
using System;
using ApiQuanLyNhaThuoc.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiQuanLyNhaThuoc.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThanhPho")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.DanhMuc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            Id = "DM111",
                            CreatedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4292),
                            MoTa = "Thuốc dị ứng",
                            ModifiedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4306),
                            TenDanhMuc = "Thuốc"
                        },
                        new
                        {
                            Id = "DM112",
                            CreatedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4307),
                            MoTa = "Thuốc da liễu",
                            ModifiedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4308),
                            TenDanhMuc = "Thuốc"
                        },
                        new
                        {
                            Id = "DM113",
                            CreatedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4347),
                            MoTa = "Thuốc hô hấp",
                            ModifiedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4348),
                            TenDanhMuc = "Thuốc"
                        },
                        new
                        {
                            Id = "DM114",
                            CreatedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4349),
                            MoTa = "Vitamin & Khoáng chất",
                            ModifiedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4350),
                            TenDanhMuc = "Thực phẩm chứng năng"
                        },
                        new
                        {
                            Id = "DM115",
                            CreatedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4351),
                            MoTa = "Hỗ trợ làm đẹp",
                            ModifiedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4351),
                            TenDanhMuc = "Thực phẩm chứng năng"
                        },
                        new
                        {
                            Id = "DM116",
                            CreatedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4352),
                            MoTa = "Dinh dưỡng",
                            ModifiedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4352),
                            TenDanhMuc = "Thực phẩm chứng năng"
                        });
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.KhachHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.NhaCungCap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TrangThaiGiaoDich")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("NhaCungCap");

                    b.HasData(
                        new
                        {
                            Id = "NCC001",
                            CreatedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4522),
                            DiaChi = "123 Lê Lợi",
                            Email = "longchaugv@gmail.com",
                            ModifiedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4523),
                            QuocGia = "Việt Nam",
                            SoDienThoai = "0123456789",
                            TenNhaCungCap = "Nhà thuốc Long Châu",
                            ThanhPho = "Hồ Chí Minh",
                            TrangThaiGiaoDich = 1,
                            Website = "longchau.com"
                        });
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.NhanVien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("HeSoLuong")
                        .HasColumnType("double");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.SanPham", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AnhSanPham")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DanhMucId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DonViTinhNhoNhat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DuongDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HangSanXuat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoatChatChinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiThuoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaThuoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaVach")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mota")
                        .HasColumnType("longtext");

                    b.Property<string>("NuocSanXuat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuyCachDongGoi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SoDangKy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TrangThaiBan")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.ChiTietGiamGia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("GiamGia")
                        .HasColumnType("double");

                    b.Property<string>("KhuyenMaiId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhienBanSanPhamId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KhuyenMaiId");

                    b.HasIndex("PhienBanSanPhamId");

                    b.ToTable("ChiTietGiamGia");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.ChiTietHoaDonBanHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Gia")
                        .HasColumnType("double");

                    b.Property<string>("HoaDonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhienBanSanPhamId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("SoLuong")
                        .HasColumnType("double");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("PhienBanSanPhamId");

                    b.ToTable("ChiTietHoaDonBanHang");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.ChiTietHoaDonDatHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("HoaDonDatHangId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhienBanSanPhamId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("SoLuongDaNhap")
                        .HasColumnType("double");

                    b.Property<double>("SoLuongDat")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonDatHangId");

                    b.HasIndex("PhienBanSanPhamId");

                    b.ToTable("ChiTietHoaDonDatHang");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.ChiTietHoaDonNhapHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("HoaDonNhapHangId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoHangId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhienBanSanPhamId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("SoLuongNhap")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonNhapHangId");

                    b.HasIndex("LoHangId");

                    b.HasIndex("PhienBanSanPhamId");

                    b.ToTable("ChiTietHoaDonNhapHang");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HangTonKho", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KhoHangId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoHangId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhienBanSanPhamId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("SoLuongCoTheBan")
                        .HasColumnType("double");

                    b.Property<double>("SoLuongDangVe")
                        .HasColumnType("double");

                    b.Property<double>("SoLuongTrongKho")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("KhoHangId");

                    b.HasIndex("LoHangId");

                    b.HasIndex("PhienBanSanPhamId");

                    b.ToTable("HangTonKho");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonBanHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KhachHangId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KhuyenMaiId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("Thue")
                        .HasColumnType("double");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("KhuyenMaiId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HoaDonBanHang");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonDatHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCungCapId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("Thue")
                        .HasColumnType("double");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrangThaiNhap")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HoaDonDatHang");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonNhapHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HoaDonDatHangId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KhoHangId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCungCapId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("Thue")
                        .HasColumnType("double");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonDatHangId");

                    b.HasIndex("KhoHangId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HoaDonNhapHang");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.KhoHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhienBanSanPhamId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ViTriLuuTru")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PhienBanSanPhamId");

                    b.ToTable("KhoHang");

                    b.HasData(
                        new
                        {
                            Id = "KHO001",
                            CreatedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4550),
                            ModifiedDate = new DateTime(2024, 9, 27, 16, 12, 40, 981, DateTimeKind.Local).AddTicks(4550),
                            ViTriLuuTru = "Chi nhánh mặc định"
                        });
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.KhuyenMai", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.LoHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KhoHangId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCungCapId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhienBanSanPhamId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("SoLuongQuyDoi")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("KhoHangId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("PhienBanSanPhamId");

                    b.ToTable("LoHang");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DonViQuyDoi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("GiaBanQuyDoi")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GiaNhapQuyDoi")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("KhoiLuong")
                        .HasColumnType("longtext");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaVach")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SanPhamId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("SoLuong")
                        .HasColumnType("double");

                    b.Property<string>("TenQuyDoi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TrangThaiBan")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.ToTable("PhienBanSanPham");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.SanPham", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.ChiTietGiamGia", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("KhuyenMaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", "PhienBanSanPham")
                        .WithMany()
                        .HasForeignKey("PhienBanSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("PhienBanSanPham");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.ChiTietHoaDonBanHang", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonBanHang", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", "PhienBanSanPham")
                        .WithMany()
                        .HasForeignKey("PhienBanSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("PhienBanSanPham");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.ChiTietHoaDonDatHang", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonDatHang", "HoaDonDatHang")
                        .WithMany("ChiTietHoaDonDatHangs")
                        .HasForeignKey("HoaDonDatHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", "PhienBanSanPham")
                        .WithMany("ChiTietHoaDonDatHangs")
                        .HasForeignKey("PhienBanSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonDatHang");

                    b.Navigation("PhienBanSanPham");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.ChiTietHoaDonNhapHang", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonNhapHang", "HoaDonNhapHang")
                        .WithMany("ChiTietHoaDonNhapHangs")
                        .HasForeignKey("HoaDonNhapHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.LoHang", "LoHang")
                        .WithMany()
                        .HasForeignKey("LoHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", "PhienBanSanPham")
                        .WithMany("ChiTietHoaDonNhapHangs")
                        .HasForeignKey("PhienBanSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonNhapHang");

                    b.Navigation("LoHang");

                    b.Navigation("PhienBanSanPham");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HangTonKho", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.KhoHang", "KhoHang")
                        .WithMany("HangTonKhos")
                        .HasForeignKey("KhoHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.LoHang", "LoHang")
                        .WithMany()
                        .HasForeignKey("LoHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", "PhienBanSanPham")
                        .WithMany()
                        .HasForeignKey("PhienBanSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoHang");

                    b.Navigation("LoHang");

                    b.Navigation("PhienBanSanPham");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonBanHang", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("KhuyenMaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonDatHang", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonNhapHang", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonDatHang", "HoaDonDatHang")
                        .WithMany("HoaDonNhapHangs")
                        .HasForeignKey("HoaDonDatHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.KhoHang", "KhoHang")
                        .WithMany("HoaDonNhapHangs")
                        .HasForeignKey("KhoHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany("HoaDonNhapHangs")
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonDatHang");

                    b.Navigation("KhoHang");

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.KhoHang", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", null)
                        .WithMany("KhoHangs")
                        .HasForeignKey("PhienBanSanPhamId");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.LoHang", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.KhoHang", "KhoHang")
                        .WithMany("LoHangs")
                        .HasForeignKey("KhoHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany("LoHangs")
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", "PhienBanSanPham")
                        .WithMany("LoHangs")
                        .HasForeignKey("PhienBanSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoHang");

                    b.Navigation("NhaCungCap");

                    b.Navigation("PhienBanSanPham");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.SanPham", "SanPham")
                        .WithMany("DanhSachPhienBan")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApiQuanLyNhaThuoc.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.NhaCungCap", b =>
                {
                    b.Navigation("HoaDonNhapHangs");

                    b.Navigation("LoHangs");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Entities.SanPham", b =>
                {
                    b.Navigation("DanhSachPhienBan");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonDatHang", b =>
                {
                    b.Navigation("ChiTietHoaDonDatHangs");

                    b.Navigation("HoaDonNhapHangs");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.HoaDonNhapHang", b =>
                {
                    b.Navigation("ChiTietHoaDonNhapHangs");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.KhoHang", b =>
                {
                    b.Navigation("HangTonKhos");

                    b.Navigation("HoaDonNhapHangs");

                    b.Navigation("LoHangs");
                });

            modelBuilder.Entity("ApiQuanLyNhaThuoc.Models.Models.Entities.PhienBanSanPham", b =>
                {
                    b.Navigation("ChiTietHoaDonDatHangs");

                    b.Navigation("ChiTietHoaDonNhapHangs");

                    b.Navigation("KhoHangs");

                    b.Navigation("LoHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
